### ISSUE TITLE
So I have started docker container and connected to slack with token...now what?

### ISSUE THREAD

**Issue by wanfuse123** [torgeirl/eliza#1]
Hi!

So the container is started and I have connected successfully with my token to slack. How do i actually interact with eliza?

Your directions are missing this important detail. 

thanks for the help!

steve

**Comment by torgeirl** [comment]
Hi Steve,

Just add her to a channel or send her a direct message.

If you want to see what's under the hood for inspiration on changing her or making your on bot, take a look at the files bot/event_handler.py and bot/messenger.py


Cheers,
Torgeir
